// UPSTREAM: OpenRA.Game/ObjectCreator.cs @7d57605 L21-168(按名实例化/类型查找)
//          + OpenRA.Game/Traits/TraitsInterfaces.cs L342-351(TraitInfo 基类)
//          Name-based instantiation/type lookup + the TraitInfo base class.
//
// C# 侧程序集反射扫描(FindType/GetTypesImplementing)在此替换为静态注册表:
// 每个 Info 类在 gen/ 注册源中登记(RecordDesc + 工厂),名字即 yaml 中的
// trait 名 + "Info" 后缀(ActorInfo.LoadTraitInfo 的拼名约定)。
// The C# assembly-reflection scan (FindType/GetTypesImplementing) is replaced
// by a static registry: every Info class registers (RecordDesc + factory) in
// the gen/ registration sources, keyed by the yaml trait name + "Info" suffix
// (the name-joining convention of ActorInfo.LoadTraitInfo).
#pragma once
import std;
#include "meta/field_desc.hpp"

namespace ora::meta {

/// 可加载记录对象的共同最小基(工厂产物;等价 C# object 的强类型落点;
/// sim::TraitInfo / rules 侧 Info 类均派生自此)
/// The minimal common base of loadable record objects (the factory product;
/// the typed landing of the C# object). sim::TraitInfo and the rules-side
/// Info classes derive from it.
class RecordObject {
 public:
  virtual ~RecordObject() = default;

  /// 本类型的记录描述(等价 C# GetType();沿 base 链收集字段用)
  /// The record descriptor of this type (the C# GetType() equivalent; used
  /// to collect fields along the base chain).
  virtual const RecordDesc& record_desc() const = 0;
};

/// 类型注册表(ObjectCreator 的 FindType/CreateObject 等价)
/// The type registry (the ObjectCreator FindType/CreateObject equivalent).
class TypeRegistry {
 public:
  /// 注册一条类型描述 + 默认构造工厂(schema_dumper 生成的 gen/ 源调用)
  /// Register one type descriptor + default-construct factory (invoked from
  /// the gen/ sources generated by schema_dumper).
  static void Register(RecordDesc desc, std::function<std::unique_ptr<RecordObject>()> fn_factory);

  /// FindType:按类名查找描述(未注册返回 nullptr)
  /// FindType: look up a descriptor by class name (nullptr when unknown).
  static const RecordDesc* FindType(std::string_view str_class_name);

  /// CreateObject:默认构造实例(ObjectCreator.CreateBasic;未知类型返回 nullptr,
  /// 调用方决定抛 InvalidOperationException 还是走 linter 报错路径)
  /// CreateObject: default-construct an instance (ObjectCreator.CreateBasic;
  /// nullptr for unknown types — the caller decides between
  /// InvalidOperationException and the linter error path).
  static std::unique_ptr<RecordObject> CreateObject(std::string_view str_class_name);

  /// 测试用:清空注册表(引擎路径不调用)
  /// Tests only: clear the registry (engine paths never call this).
  static void ClearForTest();

  /// 全部已注册名字(诊断/校验用)
  /// All registered names (for diagnostics/validation).
  static std::vector<std::string_view> AllTypeNames();
};

}  // namespace ora::meta
