// UPSTREAM: OpenRA.Game/Network/OrderIO.cs @7d57605(实现部分)
//          The implementation half of OrderIO.cs.
#include "net/order_io.hpp"

namespace ora::net {

namespace {
std::int32_t ReadInt32At(const std::vector<std::uint8_t>& v,
                         std::size_t offset) {
  return static_cast<std::int32_t>(
      static_cast<std::uint32_t>(v[offset]) |
      (static_cast<std::uint32_t>(v[offset + 1]) << 8) |
      (static_cast<std::uint32_t>(v[offset + 2]) << 16) |
      (static_cast<std::uint32_t>(v[offset + 3]) << 24));
}

std::int64_t ReadInt64At(const std::vector<std::uint8_t>& v,
                         std::size_t offset) {
  std::uint64_t out = 0;
  for (unsigned i = 0; i < 8; ++i)
    out |= static_cast<std::uint64_t>(v[offset + i]) << (i * 8);
  return static_cast<std::int64_t>(out);
}

std::uint64_t ReadUInt64At(const std::vector<std::uint8_t>& v,
                           std::size_t offset) {
  return static_cast<std::uint64_t>(ReadInt64At(v, offset));
}

float ReadFloatAt(const std::vector<std::uint8_t>& v, std::size_t offset) {
  const auto bits = static_cast<std::uint32_t>(ReadInt32At(v, offset));
  float f;
  std::memcpy(&f, &bits, 4);
  return f;
}
}  // namespace

// ———— OrderPacket ————

OrderPacket::OrderPacket(const std::vector<const Order*>& vec_orders) {
  ByteWriter w;
  for (const Order* o : vec_orders) {
    // Orders may refer to actors that no longer exist by the time
    // that the order is resolved. In order to ensure consistent
    // behaviour between local and remote clients, it is simplest
    // to always serialize / deserialize orders, instead of storing
    // the Order objects directly on the local client.
    const auto bytes = o->Serialize();
    w.WriteBytes(bytes);
  }
  vec_data_ = w.TakeBytes();
}

std::vector<std::unique_ptr<Order>> OrderPacket::GetOrders(
    sim::World* world) const {
  std::vector<std::unique_ptr<Order>> out;
  if (vec_data_.empty())
    return out;

  // Order deserialization depends on the current world state,
  // so must be deferred until we are ready to consume them.
  ByteReader r(vec_data_);
  while (r.Remaining() > 0) {
    auto o = Order::Deserialize(world, r);
    if (o != nullptr)
      out.push_back(std::move(o));
  }
  return out;
}

std::vector<std::uint8_t> OrderPacket::Serialize(int frame) const {
  ByteWriter w;
  w.Write(frame);
  w.WriteBytes(vec_data_);
  return w.TakeBytes();
}

OrderPacket OrderPacket::Combine(
    const std::vector<const OrderPacket*>& packets) {
  std::vector<std::uint8_t> data;
  for (const auto* packet : packets)
    data.insert(data.end(), packet->vec_data_.begin(),
                packet->vec_data_.end());
  return OrderPacket::FromBytes(std::move(data));
}

// ———— OrderIO ————

std::vector<std::uint8_t> OrderIO::SerializeSync(const SyncPacketData& data) {
  ByteWriter w;
  w.Write(data.frame);
  w.Write(static_cast<std::uint8_t>(OrderType::SyncHash));
  w.Write(data.sync_hash);
  w.Write(data.uint8_defeat_state);
  return w.TakeBytes();
}

std::vector<std::uint8_t> OrderIO::SerializePingResponse(
    std::int64_t timestamp, std::uint8_t queue_length) {
  ByteWriter w;
  w.Write(static_cast<std::int32_t>(0));
  w.Write(static_cast<std::uint8_t>(OrderType::Ping));
  w.Write(timestamp);
  w.Write(queue_length);
  return w.TakeBytes();
}

bool OrderIO::TryParseDisconnect(const Packet& packet,
                                 DisconnectData& out) {
  // Valid Disconnect packets are only ever generated by the server
  if (packet.from_client != 0 ||
      packet.vec_data.size() != Order::DisconnectOrderLength + 4 ||
      packet.vec_data[4] != static_cast<std::uint8_t>(OrderType::Disconnect)) {
    out = DisconnectData{};
    return false;
  }

  out.frame = ReadInt32At(packet.vec_data, 0);
  out.client_id = ReadInt32At(packet.vec_data, 5);
  return true;
}

bool OrderIO::TryParseSync(const std::vector<std::uint8_t>& packet,
                           SyncPacketData& out) {
  if (packet.size() != 4 + Order::SyncHashOrderLength ||
      packet[4] != static_cast<std::uint8_t>(OrderType::SyncHash)) {
    out = SyncPacketData{};
    return false;
  }

  out.frame = ReadInt32At(packet, 0);
  out.sync_hash = ReadInt32At(packet, 5);
  out.uint8_defeat_state = ReadUInt64At(packet, 9);
  return true;
}

bool OrderIO::TryParseTickScale(const Packet& packet, float& out_scale) {
  // Valid tick scale commands are only ever generated by the server
  if (packet.from_client != 0 || packet.vec_data.size() != 9 ||
      packet.vec_data[4] != static_cast<std::uint8_t>(OrderType::TickScale)) {
    out_scale = 1;
    return false;
  }

  // Valid tick scale packets always have frame 0
  const auto frame = ReadInt32At(packet.vec_data, 0);
  if (frame != 0) {
    out_scale = 1;
    return false;
  }

  out_scale = ReadFloatAt(packet.vec_data, 5);
  return true;
}

bool OrderIO::TryParsePingRequest(const Packet& packet,
                                  std::int64_t& out_timestamp) {
  // Valid Ping requests are only ever generated by the server
  if (packet.from_client != 0 || packet.vec_data.size() != 13 ||
      packet.vec_data[4] != static_cast<std::uint8_t>(OrderType::Ping)) {
    out_timestamp = 0;
    return false;
  }

  // Valid Ping packets always have frame 0
  const auto frame = ReadInt32At(packet.vec_data, 0);
  if (frame != 0) {
    out_timestamp = 0;
    return false;
  }

  out_timestamp = ReadInt64At(packet.vec_data, 5);
  return true;
}

bool OrderIO::TryParseAck(const Packet& packet, int& out_frame,
                          std::uint8_t& out_count) {
  // Ack packets are only accepted from the server
  if (packet.from_client != 0 || packet.vec_data.size() != 6 ||
      packet.vec_data[4] != static_cast<std::uint8_t>(OrderType::Ack)) {
    out_frame = 0;
    out_count = 0;
    return false;
  }

  out_frame = ReadInt32At(packet.vec_data, 0);
  out_count = packet.vec_data[5];
  return true;
}

bool OrderIO::TryParseOrderPacket(const std::vector<std::uint8_t>& packet,
                                  int& out_frame, OrderPacket& out_orders) {
  // Not a valid packet
  if (packet.size() < 4) {
    out_frame = 0;
    out_orders = OrderPacket{};
    return false;
  }

  // Wrong packet type
  if (packet.size() >= 5 &&
      (packet[4] == static_cast<std::uint8_t>(OrderType::Disconnect) ||
       packet[4] == static_cast<std::uint8_t>(OrderType::SyncHash))) {
    out_frame = 0;
    out_orders = OrderPacket{};
    return false;
  }

  out_frame = ReadInt32At(packet, 0);

  // PERF: Skip empty order frames, often per client each frame
  if (packet.size() > 4) {
    out_orders = OrderPacket::FromBytes(
        std::vector<std::uint8_t>(packet.begin() + 4, packet.end()));
  } else {
    out_orders = OrderPacket{};
  }
  return true;
}

}  // namespace ora::net
