// formats_test — Phase 4 formats 第一编验收:FastByteReader/SpanReader +
// LCW(五 case 解码/Encode)/XOR(六 case)/RLE0/LZO(minilzo 移植)/CRC32
// 纯逻辑断言;合成 shpTD(TrimmedFrame 裁剪/全零帧)与 tmp TD/RA/TS 夹具;
// mods 全量 .shp/.pal 资产与合成夹具/编解码向量对上游 C# oracle 黄金
// 逐行对拍(tests/golden_formats.txt,由 tools/golden_gen -- fmt 再生);
// SheetBuilder::Add(ISpriteFrame) 接线断言(D47 遗留)。
// formats_test — the Phase 4 first-formats-batch acceptance: pure-logic
// assertions on FastByteReader/SpanReader + LCW (the five decoder cases /
// Encode) / XOR (the six cases) / RLE0 / LZO (the minilzo port) / CRC32;
// the synthetic shpTD (TrimmedFrame bounds-trimming / all-zero frames) and
// tmp TD/RA/TS fixtures; a line-by-line differential of the all-mods
// .shp/.pal assets plus the synthetic fixtures and codec vectors against
// the upstream C# oracle golden (tests/golden_formats.txt, regenerated by
// tools/golden_gen -- fmt); and the SheetBuilder::Add(ISpriteFrame)
// wiring assertions (the D47 leftover).
import std;
#include <cstdio>  // stderr 为宏,不穿越 import 边界(规范允许的并用正形态) | stderr is a macro; the spec-sanctioned mixed form

#include "formats/crc32.hpp"
#include "formats/fast_byte_reader.hpp"
#include "formats/lcw.hpp"
#include "formats/lzo.hpp"
#include "formats/rle_zeros.hpp"
#include "formats/shp_d2.hpp"
#include "formats/shp_td.hpp"
#include "formats/shp_ts.hpp"
#include "formats/span_reader.hpp"
#include "formats/tmp_ra.hpp"
#include "formats/tmp_td.hpp"
#include "formats/tmp_ts.hpp"
#include "formats/xor_delta.hpp"
#include "gfx/palette.hpp"
#include "gfx/sheet.hpp"
#include "meta/dump_format.hpp"

namespace {

std::int32_t int4_failures = 0;

#define ORA_CHECK(...)                                                         \
  do {                                                                         \
    if (!(__VA_ARGS__)) {                                                      \
      std::println(stderr, "FAIL {}:{} {}", __FILE__, __LINE__, #__VA_ARGS__); \
      ++int4_failures;                                                         \
    }                                                                          \
  } while (0)

// ———— 小工具 / Small helpers ————

std::vector<std::byte> ReadFileBytes(const std::string& str_path) {
  auto stream_file = std::ifstream{str_path, std::ios::binary};
  if (!stream_file)
    throw std::runtime_error("cannot open " + str_path);
  auto str_bytes = std::string{std::istreambuf_iterator<char>{stream_file}, std::istreambuf_iterator<char>{}};
  auto vec_out = std::vector<std::byte>(str_bytes.size());
  if (!str_bytes.empty())
    std::memcpy(vec_out.data(), str_bytes.data(), str_bytes.size());
  return vec_out;
}

std::vector<std::byte> HexToBytes(std::string_view str_hex) {
  auto vec_out = std::vector<std::byte>{};
  if (str_hex == "-")
    return vec_out;
  ORA_CHECK(str_hex.size() % 2 == 0);
  for (std::size_t st_i = 0; st_i + 1 < str_hex.size(); st_i += 2) {
    const auto char_digit = [](char char_c) {
      if (char_c >= '0' && char_c <= '9') return char_c - '0';
      if (char_c >= 'A' && char_c <= 'F') return char_c - 'A' + 10;
      throw std::runtime_error("bad hex digit");
    };
    vec_out.push_back(static_cast<std::byte>(char_digit(str_hex[st_i]) * 16 + char_digit(str_hex[st_i + 1])));
  }
  return vec_out;
}

std::string BytesToHexLower(const std::byte* ptr_data, std::size_t st_len) {
  static constexpr const char* kDigits = "0123456789ABCDEF";
  auto str_out = std::string{};
  str_out.reserve(st_len * 2);
  for (std::size_t st_i = 0; st_i < st_len; st_i++) {
    const auto uint1_v = static_cast<std::uint8_t>(ptr_data[st_i]);
    str_out.push_back(kDigits[uint1_v >> 4]);
    str_out.push_back(kDigits[uint1_v & 0xF]);
  }
  return str_out;
}

std::string BytesToHexLower(const std::span<const std::byte> vec_data) {
  return vec_data.empty() ? std::string{"-"} : BytesToHexLower(vec_data.data(), vec_data.size());
}

std::vector<std::byte> MakeBytes(std::initializer_list<std::uint8_t> vec_values) {
  auto vec_out = std::vector<std::byte>{};
  vec_out.reserve(vec_values.size());
  for (const auto uint1_v : vec_values)
    vec_out.push_back(static_cast<std::byte>(uint1_v));
  return vec_out;
}

// ———— 纯逻辑:编解码器 / Pure logic: the codecs ————

void TestFastByteReader() {
  const auto vec_src = MakeBytes({0x01, 0x02, 0x03, 0x04, 0x05});
  auto reader = ora::fmt::FastByteReader{vec_src};
  ORA_CHECK(!reader.Done());
  ORA_CHECK(reader.Remaining() == 5);
  ORA_CHECK(static_cast<std::uint8_t>(reader.ReadByte()) == 0x01);
  ORA_CHECK(reader.ReadWord() == 0x0302);  // x | next<<8 | x | next<<8
  ORA_CHECK(reader.Remaining() == 2);

  auto vec_dest = std::vector<std::byte>(3);
  reader.CopyTo(vec_dest, 1, 2);
  ORA_CHECK(vec_dest == MakeBytes({0x00, 0x04, 0x05}));
  ORA_CHECK(reader.Done());
}

void TestRLEZeros() {
  // cmd 字面量 + (0,count) 零段交错 | literal cmd bytes interleaved with
  // (0, count) zero runs
  const auto vec_src = MakeBytes({0x01, 0x02, 0x00, 0x03, 0x05});
  auto vec_dest = std::vector<std::byte>(8, std::byte{0xAA});
  ora::fmt::rle_zeros::DecodeInto(vec_src, vec_dest, 0);
  ORA_CHECK(vec_dest == MakeBytes({0x01, 0x02, 0x00, 0x00, 0x00, 0x05, 0xAA, 0xAA}));

  // 越界零段 = 上游 IndexOutOfRange 的等价抛点 | an out-of-bounds zero run
  // hits the equivalent throw of upstream's IndexOutOfRange
  auto vec_dest_small = std::vector<std::byte>(2);
  auto b_threw = false;
  try {
    ora::fmt::rle_zeros::DecodeInto(vec_src, vec_dest_small, 1);
  } catch (const std::runtime_error&) {
    b_threw = true;
  }
  ORA_CHECK(b_threw);
}

void TestXORDelta() {
  using ora::fmt::xor_delta::DecodeInto;

  // case5(0x01..0x7F 字面量段)+ 终止(0x80 0x00 0x00 0x00)。
  // case 5 (a 0x01..0x7F literal span) + termination.
  auto vec_src = MakeBytes({0x05, 0x10, 0x20, 0x30, 0x40, 0x50, 0x80, 0x00, 0x00, 0x00});
  auto vec_dest = std::vector<std::byte>(8, std::byte{0x0F});
  ORA_CHECK(DecodeInto(vec_src, vec_dest, 0) == 5);
  ORA_CHECK(vec_dest == MakeBytes({0x1F, 0x2F, 0x3F, 0x40 ^ 0x0F, 0x5F, 0x0F, 0x0F, 0x0F}));

  // case6(单值 XOR)。| case 6 (a single-value XOR).
  vec_src = MakeBytes({0x00, 0x04, 0xFF, 0x80, 0x00, 0x00, 0x00});
  std::ranges::fill(vec_dest, std::byte{0x11});
  ORA_CHECK(DecodeInto(vec_src, vec_dest, 0) == 4);
  ORA_CHECK(vec_dest == MakeBytes({0xEE, 0xEE, 0xEE, 0xEE, 0x11, 0x11, 0x11, 0x11}));

  // case1(短跳)+ case2(word 跳过)。| case 1 (a short skip) + case 2 (a
  // word skip).
  vec_src = MakeBytes({0x83, 0x80, 0x02, 0x00, 0x80, 0x00, 0x00, 0x00});
  std::ranges::fill(vec_dest, std::byte{0});
  vec_dest[2] = std::byte{0x7F};
  vec_dest[7] = std::byte{0x55};
  ORA_CHECK(DecodeInto(vec_src, vec_dest, 0) == 5);
  ORA_CHECK(vec_dest == MakeBytes({0x00, 0x00, 0x7F, 0x00, 0x00, 0x00, 0x00, 0x55}));

  // case3(word 计数字面量段)。| case 3 (a word-counted literal span).
  vec_src = MakeBytes({0x80, 0x02, 0x80, 0x0A, 0x14, 0x80, 0x00, 0x00, 0x00});
  std::ranges::fill(vec_dest, std::byte{0x01});
  ORA_CHECK(DecodeInto(vec_src, vec_dest, 0) == 2);
  const auto vec_expect_c3 = MakeBytes({0x0B, 0x15});
  ORA_CHECK(std::ranges::equal(std::span<const std::byte>{vec_dest}.first(2), std::span<const std::byte>{vec_expect_c3}));

  // case4(word 计数单值段)。| case 4 (a word-counted single-value span).
  vec_src = MakeBytes({0x80, 0x03, 0xC0, 0xAA, 0x80, 0x00, 0x00, 0x00});
  std::ranges::fill(vec_dest, std::byte{0x10});
  ORA_CHECK(DecodeInto(vec_src, vec_dest, 0) == 3);
  const auto vec_expect_c4 = MakeBytes({0xBA, 0xBA, 0xBA});
  ORA_CHECK(std::ranges::equal(std::span<const std::byte>{vec_dest}.first(3), std::span<const std::byte>{vec_expect_c4}));
}

void TestLCW() {
  using ora::fmt::lcw::DecodeInto;

  // case1:0x80|n 字面量段 + 0x80 终止。| case 1: a 0x80|n literal span +
  // the 0x80 terminator.
  auto vec_src = MakeBytes({0x83, 0xAA, 0xBB, 0xCC, 0x80});
  auto vec_dest = std::vector<std::byte>(3);
  ORA_CHECK(DecodeInto(vec_src, vec_dest) == 3);
  ORA_CHECK(vec_dest == MakeBytes({0xAA, 0xBB, 0xCC}));

  // case4(0xFE):单字节重复 word 计数。| case 4 (0xFE): a word-counted
  // single-byte repeat.
  vec_src = MakeBytes({0xFE, 0x05, 0x00, 0x77, 0x80});
  vec_dest.assign(5, std::byte{0});
  ORA_CHECK(DecodeInto(vec_src, vec_dest) == 5);
  ORA_CHECK(vec_dest == MakeBytes({0x77, 0x77, 0x77, 0x77, 0x77}));

  // case3(0xC0|n-3):自绝对 srcIndex 拷贝。| case 3 (0xC0|n-3): copy from
  // an absolute srcIndex.
  vec_src = MakeBytes({0x84, 0x11, 0x22, 0x33, 0x44, 0xC1, 0x00, 0x00, 0x80});
  vec_dest.assign(8, std::byte{0});
  ORA_CHECK(DecodeInto(vec_src, vec_dest) == 8);
  ORA_CHECK(vec_dest == MakeBytes({0x11, 0x22, 0x33, 0x44, 0x11, 0x22, 0x33, 0x44}));

  // case2:相对回拷(dist=1 的 RLE 展开;count=4, rpos=1)。
  // case 2: a relative replicate (the dist=1 RLE expansion; count=4,
  // rpos=1).
  vec_src = MakeBytes({0x82, 0x5A, 0x21, 0x10, 0x01, 0x80});
  vec_dest.assign(6, std::byte{0});
  ORA_CHECK(DecodeInto(vec_src, vec_dest) == 6);
  ORA_CHECK(vec_dest == MakeBytes({0x5A, 0x21, 0x21, 0x21, 0x21, 0x21}));

  // dest 提前满:case2 显式返回已写字节(上游行为)。| dest fills early:
  // case 2 returns the written count explicitly (upstream behavior).
  vec_src = MakeBytes({0x10, 0x00, 0x80});
  vec_dest.assign(2, std::byte{0});
  ORA_CHECK(DecodeInto(vec_src, vec_dest) == 0);

  // case1 越界写 = 上游 Array.Copy 抛 IndexOutOfRange 的等价抛点。
  // A case-1 overflow write hits the equivalent throw of upstream's
  // Array.Copy IndexOutOfRange.
  vec_src = MakeBytes({0x83, 0x5A, 0x21, 0x33, 0x80});
  vec_dest.assign(2, std::byte{0});
  auto b_threw = false;
  try {
    DecodeInto(vec_src, vec_dest);
  } catch (const std::runtime_error&) {
    b_threw = true;
  }
  ORA_CHECK(b_threw);

  // Encode→Decode 往返(含 RLE 段)。| an Encode→Decode round trip
  // (including an RLE span).
  auto vec_pattern = std::vector<std::byte>{};
  for (auto int4_i = 0; int4_i < 40; int4_i++)
    vec_pattern.push_back(static_cast<std::byte>(int4_i * 7 % 251));
  for (auto int4_i = 0; int4_i < 300; int4_i++)
    vec_pattern.push_back(std::byte{0xAB});
  for (auto int4_i = 0; int4_i < 61; int4_i++)
    vec_pattern.push_back(static_cast<std::byte>((int4_i * int4_i) % 256));

  const auto vec_encoded = ora::fmt::lcw::Encode(vec_pattern);
  auto vec_round = std::vector<std::byte>(vec_pattern.size());
  ORA_CHECK(DecodeInto(vec_encoded, vec_round) == static_cast<std::int32_t>(vec_pattern.size()));
  ORA_CHECK(vec_round == vec_pattern);

  // Encode 确定性形态抽查:RLE 段产出 0xFE 命令头。| an Encode shape
  // spot-check: the RLE span emits the 0xFE command header.
  ORA_CHECK(vec_encoded.front() == static_cast<std::byte>(0x80 | 40));
  bool b_has_rle = false;
  for (std::size_t st_i = 0; st_i + 3 < vec_encoded.size(); st_i++)
    if (vec_encoded[st_i] == std::byte{0xFE}) {
      b_has_rle = true;
      break;
    }
  ORA_CHECK(b_has_rle);
}

void TestCRC32() {
  // 标准向量在 crc32.hpp 内 static_assert;此处补分段链式一致性。
  // The standard vector is static_asserted in crc32.hpp; here the
  // segmented-chaining equivalence.
  auto arr_check = std::vector<std::byte>{};
  for (const char char_c : std::string_view{"123456789"})
    arr_check.push_back(static_cast<std::byte>(char_c));
  const auto uint4_whole = ora::fmt::CRC32::Calculate(arr_check);
  const auto uint4_chained = ora::fmt::CRC32::Finish(
      ora::fmt::CRC32::Update(ora::fmt::CRC32::Update(0xFFFFFFFF, std::span<const std::byte>{arr_check}.first(4)),
                              std::span<const std::byte>{arr_check}.last(5)));
  ORA_CHECK(uint4_whole == 0xCBF43926);
  ORA_CHECK(uint4_whole == uint4_chained);
}

// ———— 纯逻辑:合成 shpTD(TrimmedFrame)/ tmp 夹具 ————
// ———— Pure logic: the synthetic shpTD (TrimmedFrame) / tmp fixtures ————

std::vector<std::byte> MakeSyntheticShpTD(std::span<const std::byte> vec_frame, std::uint16_t uint2_w,
                                          std::uint16_t uint2_h) {
  auto vec_encoded = ora::fmt::lcw::Encode(vec_frame);
  const auto uint4_data_offset = 14u + 8u * 3u;
  auto vec_file = std::vector<std::byte>(uint4_data_offset + vec_encoded.size());

  const auto put_u16 = [&vec_file](std::size_t st_pos, std::uint16_t uint2_v) {
    vec_file[st_pos] = static_cast<std::byte>(uint2_v & 0xFF);
    vec_file[st_pos + 1] = static_cast<std::byte>(uint2_v >> 8);
  };
  const auto put_u32 = [&vec_file](std::size_t st_pos, std::uint32_t uint4_v) {
    for (auto int4_i = 0; int4_i < 4; int4_i++)
      vec_file[st_pos + static_cast<std::size_t>(int4_i)] = static_cast<std::byte>(uint4_v >> (8 * int4_i));
  };

  put_u16(0, 1);      // imageCount
  put_u16(6, uint2_w);
  put_u16(8, uint2_h);
  // 帧 1:LCW 格式 | frame 1: the LCW format
  put_u32(14, uint4_data_offset | (0x80u << 24));
  // eof 头:FileOffset = 文件长 | the eof header: FileOffset = file length
  put_u32(22, static_cast<std::uint32_t>(vec_file.size()));

  std::ranges::copy(vec_encoded, vec_file.begin() + static_cast<std::ptrdiff_t>(uint4_data_offset));
  return vec_file;
}

void TestSyntheticShpTD() {
  // 帧 1:24×24,中央 8×8 非零 → TrimmedFrame 裁剪,Offset (0,0)。
  // Frame 1: 24×24 with a centered 8×8 of non-zero pixels — TrimmedFrame
  // trims it with Offset (0,0).
  constexpr std::int32_t int4_w = 24, int4_h = 24;
  auto vec_frame = std::vector<std::byte>(int4_w * int4_h);
  for (auto int4_y = 8; int4_y < 16; int4_y++)
    for (auto int4_x = 8; int4_x < 16; int4_x++)
      vec_frame[static_cast<std::size_t>(int4_y * int4_w + int4_x)] =
          static_cast<std::byte>(int4_y * 8 + int4_x);

  auto vec_frames = std::vector<std::unique_ptr<ora::gfx::ISpriteFrame>>{};
  ORA_CHECK(ora::fmt::TryParseShpTD(MakeSyntheticShpTD(vec_frame, int4_w, int4_h), vec_frames));
  ORA_CHECK(vec_frames.size() == 1);
  const auto& frame = *vec_frames.front();
  ORA_CHECK(frame.Type() == ora::gfx::SpriteFrameType::Indexed8);
  ORA_CHECK(frame.Size() == ora::int2{8, 8});
  ORA_CHECK(frame.FrameSize() == ora::int2{int4_w, int4_h});
  ORA_CHECK(frame.Offset().X == 0.0f && frame.Offset().Y == 0.0f);
  ORA_CHECK(frame.Data().size() == 64);
  ORA_CHECK(frame.Data()[0] == std::byte{8 * 8 + 8});
  ORA_CHECK(frame.Data()[63] == std::byte{15 * 8 + 15});
  ORA_CHECK(frame.DisableExportPadding() == false);

  // 帧 2:全零 → Size (0,0)、Data 空(上游 TrimmedFrame 的负包围盒分支)。
  // Frame 2: all-zero — Size (0,0) with empty Data (upstream
  // TrimmedFrame's negative-bounding-box branch).
  auto vec_blank = std::vector<std::byte>(int4_w * int4_h);
  ORA_CHECK(ora::fmt::TryParseShpTD(MakeSyntheticShpTD(vec_blank, int4_w, int4_h), vec_frames));
  ORA_CHECK(vec_frames.size() == 1);
  ORA_CHECK(vec_frames.front()->Size() == ora::int2{0, 0});
  ORA_CHECK(vec_frames.front()->FrameSize() == ora::int2{0, 0});  // 无裁剪直通 Size 默认 | pass-through keeps the default
  ORA_CHECK(vec_frames.front()->Data().empty());

  // 判定负例:随机短字节与空输入。| negative probes: short random bytes
  // and empty input.
  // 判定负例:随机短字节与空输入(截断流处上游同样抛 EndOfStream,
  // 此处只取可完整判定的形态)。| negative probes: short random bytes
  // and empty input (a truncated stream throws EndOfStream upstream too,
  // so only fully-probeable shapes are used here).
  ORA_CHECK(!ora::fmt::IsShpTD(MakeBytes({0x01, 0x00, 0x00, 0x00})));
  ORA_CHECK(!ora::fmt::IsShpD2(MakeBytes({0x01, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00})));
  ORA_CHECK(!ora::fmt::IsShpTS(MakeBytes({0x01, 0x00})));
  ORA_CHECK(!ora::fmt::IsTmpTD(std::vector<std::byte>(40, std::byte{0})));
}

// ———— SheetBuilder::Add(ISpriteFrame) 接线(D47)————
// ———— The SheetBuilder::Add(ISpriteFrame) wiring (D47) ————

void TestSheetBuilderFrameAdd() {
  constexpr std::int32_t int4_w = 24, int4_h = 24;
  auto vec_frame = std::vector<std::byte>(int4_w * int4_h);
  for (auto int4_y = 8; int4_y < 16; int4_y++)
    for (auto int4_x = 8; int4_x < 16; int4_x++)
      vec_frame[static_cast<std::size_t>(int4_y * int4_w + int4_x)] =
          static_cast<std::byte>(int4_y * 8 + int4_x);

  auto vec_frames = std::vector<std::unique_ptr<ora::gfx::ISpriteFrame>>{};
  ORA_CHECK(ora::fmt::TryParseShpTD(MakeSyntheticShpTD(vec_frame, int4_w, int4_h), vec_frames));
  const auto& frame = *vec_frames.front();

  auto builder = ora::gfx::SheetBuilder{
      ora::gfx::SheetType::Indexed,
      [] {
        return std::make_unique<ora::gfx::Sheet>(ora::gfx::SheetType::Indexed, ora::int2{256, 256}, nullptr);
      },
      1};

  const auto sprite = builder.Add(frame);
  // TrimmedFrame 8×8 → bounds 尺寸 8×8;通道 Red;sheet 数据区 == 帧数据。
  // The TrimmedFrame's 8×8 → 8×8 bounds; channel Red; the sheet region
  // equals the frame data.
  ORA_CHECK(sprite.ptr_sheet == builder.Current());
  ORA_CHECK(sprite.Bounds.Width == 8 && sprite.Bounds.Height == 8);
  ORA_CHECK(sprite.kind_channel == ora::gfx::TextureChannel::Red);
  const auto vec_sheet = builder.Current()->GetData();
  for (auto int4_y = 0; int4_y < 8; int4_y++)
    for (auto int4_x = 0; int4_x < 8; int4_x++) {
      // Indexed sheet 每像素 4B;索引色落在 Red 通道 = 像素内字节 2
      // (FastCopyIntoChannel 的 kChannelMasks nuts 序)。
      // An Indexed sheet stores 4 bytes per pixel; the index color lands
      // in the Red channel = byte 2 within the pixel (FastCopyIntoChannel's
      // kChannelMasks nuts order).
      const auto st_pixel = static_cast<std::size_t>((sprite.Bounds.Y + int4_y) * 256 + sprite.Bounds.X + int4_x) * 4 + 2;
      ORA_CHECK(vec_sheet[st_pixel] == frame.Data()[static_cast<std::size_t>(int4_y * 8 + int4_x)]);
    }

  // 全零帧(Size 0)→ 空 Sprite,不占纹理。| an all-zero frame (Size 0) →
  // an empty Sprite with no texture space.
  auto vec_blank = std::vector<std::byte>(int4_w * int4_h);
  ORA_CHECK(ora::fmt::TryParseShpTD(MakeSyntheticShpTD(vec_blank, int4_w, int4_h), vec_frames));
  const auto sprite_blank = builder.Add(*vec_frames.front());
  ORA_CHECK(sprite_blank.Bounds.Width == 0 && sprite_blank.Bounds.Height == 0);
}

// ———— 黄金对拍 / The golden differential ————

using SpriteTryFn = bool (*)(std::span<const std::byte>, std::vector<std::unique_ptr<ora::gfx::ISpriteFrame>>&);

struct LoaderDef {
  std::string_view str_name;
  SpriteTryFn fn_try;
};

/// oracle 侧 LoadersFor 的同映射(各 mod mod.yaml 的 SpriteFormats 链序,
/// 未移植 loader 剔除)。
/// The same mapping as the oracle's LoadersFor (each mod's mod.yaml
/// SpriteFormats order, with unported loaders dropped).
std::vector<LoaderDef> LoadersFor(std::string_view str_mod) {
  static constexpr LoaderDef kShpD2{"ShpD2Loader", ora::fmt::TryParseShpD2};
  static constexpr LoaderDef kShpTD{"ShpTDLoader", ora::fmt::TryParseShpTD};
  static constexpr LoaderDef kTmpRA{"TmpRALoader", ora::fmt::TryParseTmpRA};
  static constexpr LoaderDef kTmpTD{"TmpTDLoader", ora::fmt::TryParseTmpTD};
  static constexpr LoaderDef kShpTS{"ShpTSLoader", ora::fmt::TryParseShpTS};
  static constexpr LoaderDef kTmpTS{"TmpTSLoader", ora::fmt::TryParseTmpTS};

  if (str_mod == "ra") return {kShpD2, kShpTD, kTmpRA, kTmpTD, kShpTS};
  if (str_mod == "cnc") return {kShpTD, kTmpTD, kShpTS, kTmpRA};
  if (str_mod == "d2k") return {kShpTD};
  if (str_mod == "ts") return {kShpTS, kTmpTS, kShpTD};
  return {kShpD2, kShpTD, kTmpRA, kTmpTD, kShpTS, kTmpTS};
}

void AppendFrameLines(const std::vector<std::unique_ptr<ora::gfx::ISpriteFrame>>& vec_frames, std::string& str_out) {
  str_out += std::format("N {}\n", vec_frames.size());
  for (const auto& ptr_frame : vec_frames) {
    const auto& frame = *ptr_frame;
    const auto vec_data = frame.Data();
    str_out += std::format("T {} W {} H {} FW {} FH {} O {} {} C {} D {} X {}\n",
                           static_cast<int>(frame.Type()), frame.Size().X, frame.Size().Y, frame.FrameSize().X,
                           frame.FrameSize().Y, ora::meta::FormatFloatNet(frame.Offset().X),
                           ora::meta::FormatFloatNet(frame.Offset().Y), ora::fmt::CRC32::Calculate(vec_data),
                           vec_data.size(), BytesToHexLower(vec_data.first(std::min<std::size_t>(32, vec_data.size()))));
  }
}

void AppendTryLines(std::span<const std::byte> vec_file, std::string_view str_name, const LoaderDef& loader,
                    std::string& str_out) {
  str_out += std::format("S {}\n", str_name);
  auto vec_frames = std::vector<std::unique_ptr<ora::gfx::ISpriteFrame>>{};
  if (loader.fn_try(vec_file, vec_frames)) {
    str_out += std::format("L {}\n", loader.str_name);
    AppendFrameLines(vec_frames, str_out);
  } else
    str_out += "L NONE\n";
}

// ———— 合成 tmp 夹具(与 oracle 构造算法逐字节一致)————
// ———— The synthetic tmp fixtures (byte-identical to the oracle's
// construction) ————

void PutU32(std::span<std::byte> vec_file, std::size_t st_pos, std::uint32_t uint4_v) {
  for (auto int4_i = 0; int4_i < 4; int4_i++)
    vec_file[st_pos + static_cast<std::size_t>(int4_i)] = static_cast<std::byte>(uint4_v >> (8 * int4_i));
}

std::vector<std::byte> MakeTileBytesTDRA(std::uint32_t uint4_idx) {
  auto vec_t = std::vector<std::byte>(16);
  for (auto int4_j = 0; int4_j < 16; int4_j++)
    vec_t[static_cast<std::size_t>(int4_j)] = static_cast<std::byte>(uint4_idx * 16 + int4_j);
  return vec_t;
}

std::vector<std::byte> MakeTmpTD() {
  auto vec_f = std::vector<std::byte>(64 + 3);
  vec_f[0] = std::byte{4};
  vec_f[2] = std::byte{4};
  PutU32(vec_f, 12, 32);          // imgStart
  PutU32(vec_f, 16, 0);           // @16 == 0
  PutU32(vec_f, 20, 0x0D1AFFFF);  // magic
  PutU32(vec_f, 24, 67);          // indexEnd
  PutU32(vec_f, 28, 64);          // indexStart
  std::ranges::copy(MakeTileBytesTDRA(0), vec_f.begin() + 32);
  std::ranges::copy(MakeTileBytesTDRA(1), vec_f.begin() + 48);
  vec_f[64] = std::byte{0};
  vec_f[65] = std::byte{255};
  vec_f[66] = std::byte{1};
  return vec_f;
}

std::vector<std::byte> MakeTmpRA() {
  auto vec_f = std::vector<std::byte>(72 + 3);
  vec_f[0] = std::byte{4};
  vec_f[2] = std::byte{4};
  PutU32(vec_f, 16, 40);  // imgStart
  PutU32(vec_f, 20, 0);   // @20 u32 == 0
  vec_f[26] = std::byte{0x73};
  vec_f[27] = std::byte{0x2C};  // @26 u16 == 0x2c73
  PutU32(vec_f, 28, 75);        // indexEnd
  PutU32(vec_f, 36, 72);        // indexStart
  std::ranges::copy(MakeTileBytesTDRA(0), vec_f.begin() + 40);
  std::ranges::copy(MakeTileBytesTDRA(1), vec_f.begin() + 56);
  vec_f[72] = std::byte{0};
  vec_f[73] = std::byte{255};
  vec_f[74] = std::byte{1};
  return vec_f;
}

std::vector<std::byte> MakeTmpTS() {
  constexpr std::size_t st_tile_len = 20 + 16 + 4 + 12 + 2 * 64;  // 180
  auto vec_f = std::vector<std::byte>(12 + 2 * st_tile_len);
  PutU32(vec_f, 0, 3);                        // templateWidth
  PutU32(vec_f, 4, 1);                        // templateHeight
  PutU32(vec_f, 8, 8);                        // tileWidth
  PutU32(vec_f, 12, 8);                       // tileHeight
  PutU32(vec_f, 16, 12);                      // offsets[0]
  PutU32(vec_f, 20, 12 + st_tile_len);        // offsets[1]
  PutU32(vec_f, 24, 0);                       // offsets[2] = 空 tile | the empty tile

  for (auto uint4_tile = 0u; uint4_tile < 2u; uint4_tile++) {
    const auto st_o = 12 + static_cast<std::size_t>(uint4_tile) * st_tile_len;
    PutU32(vec_f, st_o + 12, 8 * 8 / 2 + 52);  // IsTmpTS 魔数 @+12 | the magic @+12
    PutU32(vec_f, st_o + 20, 0);               // extraX
    PutU32(vec_f, st_o + 24, 0);               // extraY
    PutU32(vec_f, st_o + 28, 0);               // extraWidth
    PutU32(vec_f, st_o + 32, 0);               // extraHeight
    PutU32(vec_f, st_o + 36, 0);               // flags
    auto st_p = st_o + 52;
    for (auto uint4_pass = 0u; uint4_pass < 2u; uint4_pass++) {
      auto int4_width = 4;
      for (auto int4_j = 0; int4_j < 8; int4_j++) {
        for (auto int4_i = 0; int4_i < int4_width; int4_i++)
          vec_f[st_p++] = static_cast<std::byte>(uint4_tile * 31 + uint4_pass * 200 + 16 * int4_j + int4_i);
        int4_width += (int4_j < 8 / 2 - 1 ? 1 : -1) * 4;
      }
    }
  }

  return vec_f;
}

std::string BuildActualText(const std::string& str_upstream_root) {
  auto str_out = std::string{};

  // 1) mods 全部 .shp(相对路径 ordinal 排序 = oracle 枚举序)。
  // 1) Every mods .shp (relative paths in ordinal order = the oracle's
  // enumeration order).
  auto vec_shp = std::vector<std::string>{};
  for (const auto& entry : std::filesystem::recursive_directory_iterator{str_upstream_root + "/mods"}) {
    if (!entry.is_regular_file())
      continue;
    auto str_rel = entry.path().generic_string();
    if (!str_rel.ends_with(".shp"))
      continue;
    str_rel = str_rel.substr(str_upstream_root.size() + 1);
    vec_shp.push_back(str_rel);
  }
  std::ranges::sort(vec_shp);

  for (const auto& str_rel : vec_shp) {
    str_out += std::format("F {}\n", str_rel);
    const auto str_mod = str_rel.substr(5, str_rel.find('/', 5) - 5);
    const auto vec_file = ReadFileBytes(str_upstream_root + "/" + str_rel);

    auto b_hit = false;
    for (const auto& loader : LoadersFor(str_mod)) {
      auto vec_frames = std::vector<std::unique_ptr<ora::gfx::ISpriteFrame>>{};
      if (loader.fn_try(vec_file, vec_frames)) {
        str_out += std::format("L {}\n", loader.str_name);
        AppendFrameLines(vec_frames, str_out);
        b_hit = true;
        break;
      }
    }
    if (!b_hit)
      str_out += "L NONE\n";
  }

  // 2) mods 全部 .pal(ImmutablePalette(stream, [0], []) 的全 256 项)。
  // 2) Every mods .pal (all 256 entries of ImmutablePalette(stream, [0],
  // []))
  auto vec_pal = std::vector<std::string>{};
  for (const auto& entry : std::filesystem::recursive_directory_iterator{str_upstream_root + "/mods"}) {
    if (!entry.is_regular_file())
      continue;
    auto str_rel = entry.path().generic_string();
    if (!str_rel.ends_with(".pal"))
      continue;
    str_rel = str_rel.substr(str_upstream_root.size() + 1);
    vec_pal.push_back(str_rel);
  }
  std::ranges::sort(vec_pal);

  for (const auto& str_rel : vec_pal) {
    str_out += std::format("F {}\n", str_rel);
    auto vec_file = ReadFileBytes(str_upstream_root + "/" + str_rel);
    ORA_CHECK(vec_file.size() >= 768);
    const std::int32_t arr_remap_transparent[]{0};
    const auto palette = ora::gfx::ImmutablePalette{std::span<const std::byte>{vec_file}.first(768),
                                                    arr_remap_transparent, std::span<const std::int32_t>{}};
    str_out += "P";
    for (auto int4_i = 0; int4_i < 256; int4_i++)
      str_out += std::format(" {}", palette.At(int4_i));
    str_out += '\n';
  }

  // 3) 合成 tmp 夹具 | the synthetic tmp fixtures
  static constexpr LoaderDef kTmpTDDef{"TmpTDLoader", ora::fmt::TryParseTmpTD};
  static constexpr LoaderDef kTmpRADef{"TmpRALoader", ora::fmt::TryParseTmpRA};
  static constexpr LoaderDef kTmpTSDef{"TmpTSLoader", ora::fmt::TryParseTmpTS};
  AppendTryLines(MakeTmpTD(), "tmpTD_synthetic", kTmpTDDef, str_out);
  AppendTryLines(MakeTmpRA(), "tmpRA_synthetic", kTmpRADef, str_out);
  AppendTryLines(MakeTmpTS(), "tmpTS_synthetic", kTmpTSDef, str_out);

  // 4) LZO 向量(与 oracle 同集)| the LZO vectors (the same set as the oracle)
  const std::initializer_list<std::initializer_list<std::uint8_t>> vec_lzo_vectors = {
      {18, 'X', 0x55, 0x11, 0x00, 0x00},
      {22, 'a', 'b', 'c', 'd', 'e', 0x11, 0x00, 0x00},
      {0x11, 0x00, 0x00},
      {22, 'a', 'b', 'c', 'd', 'e', 0x20, 0x01, 0x00, 0x00, 0x11, 0x00, 0x00},
  };
  for (const auto& vec_v : vec_lzo_vectors) {
    auto vec_src = std::vector<std::byte>{};
    for (const auto uint1_v : vec_v)
      vec_src.push_back(static_cast<std::byte>(uint1_v));
    str_out += std::format("Z {}\n", BytesToHexLower(vec_src));

    auto vec_dest = std::vector<std::byte>(65536);
    auto uint4_out_len = std::uint32_t{0};
    const auto int4_ret = ora::fmt::lzo::DecodeInto(vec_src, 0, vec_src.size(), vec_dest, 0, uint4_out_len);
    str_out += std::format("ZR {} {} {}\n", int4_ret, uint4_out_len,
                           BytesToHexLower(std::span<const std::byte>{vec_dest}.first(uint4_out_len)));
  }

  // 5) LCW 编码向量(同 oracle 公式)| the LCW encode vector (the same
  // formula as the oracle)
  auto vec_lcw_src = std::vector<std::byte>(96);
  for (auto int4_i = 0; int4_i < 96; int4_i++)
    vec_lcw_src[static_cast<std::size_t>(int4_i)] =
        static_cast<std::byte>(int4_i < 24 ? int4_i * 3 : int4_i < 48 ? 0xAB : int4_i - 48);
  str_out += std::format("E {}\n", BytesToHexLower(vec_lcw_src));
  str_out += std::format("ER {}\n", BytesToHexLower(ora::fmt::lcw::Encode(vec_lcw_src)));

  return str_out;
}

void TestGoldenDifferential(const std::string& str_upstream_root, const std::string& str_golden_path) {
  auto vec_golden = ReadFileBytes(str_golden_path);
  auto str_golden = std::string{reinterpret_cast<const char*>(vec_golden.data()), vec_golden.size()};

  auto str_actual = BuildActualText(str_upstream_root);

  // 逐行比对(报告首 20 处差异)| compare line by line (reporting the
  // first 20 mismatches)
  auto vec_golden_lines = str_golden | std::views::split('\n') | std::ranges::to<std::vector<std::string>>();
  auto vec_actual_lines = str_actual | std::views::split('\n') | std::ranges::to<std::vector<std::string>>();
  ORA_CHECK(vec_golden_lines.back().empty());
  ORA_CHECK(vec_actual_lines.back().empty());
  vec_golden_lines.pop_back();
  vec_actual_lines.pop_back();

  ORA_CHECK(vec_golden_lines.size() == vec_actual_lines.size());
  auto int4_mismatches = 0;
  auto st_len = std::min(vec_golden_lines.size(), vec_actual_lines.size());
  for (std::size_t st_i = 0; st_i < st_len; st_i++) {
    if (vec_golden_lines[st_i] != vec_actual_lines[st_i]) {
      if (int4_mismatches < 20)
        std::println(stderr, "golden diff @line {}: expected [{}] actual [{}]", st_i + 1, vec_golden_lines[st_i],
                     vec_actual_lines[st_i]);
      ++int4_mismatches;
    }
  }
  ORA_CHECK(int4_mismatches == 0);

  std::println("formats golden: {} lines compared", st_len);
}

}  // namespace

int main(int argc, char** argv) {
  if (argc < 3) {
    std::println(stderr, "usage: formats_test <upstream-root> <golden-formats.txt>");
    return 2;
  }

  try {
    TestFastByteReader();
    TestRLEZeros();
    TestXORDelta();
    TestLCW();
    TestCRC32();
    TestSyntheticShpTD();
    TestSheetBuilderFrameAdd();
    std::println("pure-logic ok");
    TestGoldenDifferential(argv[1], argv[2]);
  } catch (const std::exception& ex) {
    std::println(stderr, "formats_test exception: {}", ex.what());
    ++int4_failures;
  }

  if (int4_failures != 0) {
    std::println(stderr, "formats_test: {} FAILURES", int4_failures);
    return 1;
  }
  std::println("formats_test: all ok");
  return 0;
}
