// UPSTREAM: 三 mod 全规则深度解析 dump(PORTING_PLAN §Phase 2 验收关卡;
//          黄金数据由 tools/schema_dumper --dump 生成,逐字节对拍)
//          The full-rules deep-parse dump of the three mods (the PORTING_PLAN
//          §Phase 2 acceptance gate; golden data generated by
//          tools/schema_dumper --dump, byte-compared).
//
// 用法 / Usage: golden_rules <mod-id> <upstream-root> <golden-file>
// 协议(schema_dumper --dump 同步实现)/ Protocol (kept in lockstep with
// schema_dumper --dump):
//   == Actor <name> ==
//   Trait <ClassName>[@<instance>]
//   <FieldName>: <formatted>
//   == Weapon <name> ==
//   ...
//   == VoiceSet <name> == / == Notification <name> ==
//   ...
//   == Music <name> ==
//   Title: <v> / Filename: <v> / Hidden: <v> / VolumeModifier: <v>
import std;
#include "game/mod_data.hpp"
#include "game/game_records.hpp"
#include "meta/dump_format.hpp"
#include "meta/field_loader.hpp"
#include "meta/generic_record.hpp"
#include <cstdio>

namespace ora::gen {
void RegisterGeneratedAll();
}  // namespace ora::gen

namespace {

using namespace ora;

/// 一条记录全部字段的 dump 行(值袋 / 内存两路)
/// Dump lines of every field of one record (both the bag and memory paths).
void DumpRecordFields(const meta::RecordObject& rec, std::vector<std::string>& vec_lines) {
  const meta::RecordDesc& desc = rec.record_desc();
  const std::vector<const meta::FieldDesc*> vec_fields = meta::CollectFields(desc);
  if (const auto* rec_generated = dynamic_cast<const meta::GeneratedRecord*>(&rec)) {
    const std::vector<meta::GenericValue>& vec_values = rec_generated->Values();
    for (std::size_t int4_i{}; int4_i < vec_fields.size() && int4_i < vec_values.size();
         int4_i++) {
      try {
        vec_lines.push_back(std::format(
            "{}: {}", vec_fields[int4_i]->str_name,
            meta::FormatValue(*vec_fields[int4_i], vec_values[int4_i])));
      } catch (const std::exception& e_fmt) {
        throw;
      }
    }
    return;
  }

  // 手写类路径:WeaponInfo/SoundInfo(内存 → 值 → 格式化;Opaque 两字段由
  // 宿主特判)
  // Hand-written-class path: WeaponInfo/SoundInfo (memory → value →
  // formatted; the two Opaque fields special-cased by the host).
  for (const meta::FieldDesc* desc_f : vec_fields) {
    const void* p_field =
        reinterpret_cast<const char*>(&rec) + desc_f->off_offset;
    meta::GenericValue val_f = meta::ReadFromMemory(*desc_f, p_field);
    if (desc_f->type == meta::FieldType::Opaque &&
        std::string_view{desc_f->str_loader} ==
            "OpenRA.GameRules.WeaponInfo.LoadProjectile") {
      const auto& rec_proj =
          *reinterpret_cast<const std::shared_ptr<meta::RecordObject>*>(p_field);
      if (rec_proj != nullptr)
        val_f = meta::GenericValue::Of(rec_proj);
    } else if (desc_f->type == meta::FieldType::Opaque &&
               std::string_view{desc_f->str_loader} ==
                   "OpenRA.GameRules.WeaponInfo.LoadWarheads") {
      const auto& vec_warheads =
          *reinterpret_cast<const std::vector<std::shared_ptr<meta::RecordObject>>*>(
              p_field);
      std::vector<meta::GenericValue> vec_vals;
      for (const auto& rec_w : vec_warheads)
        vec_vals.push_back(meta::GenericValue::Of(rec_w));
      val_f = meta::GenericValue::Of(std::move(vec_vals));
    }
    try {
      vec_lines.push_back(
          std::format("{}: {}", desc_f->str_name, meta::FormatValue(*desc_f, val_f)));
    } catch (const std::exception& e_fmt) {
      throw;
    }
  }
}

/// 子记录(嵌套记录槽)的缩进展开 / indented expansion of nested records.
void DumpTraitInto(const meta::RecordObject& rec, const std::string& str_header,
                   std::vector<std::string>& vec_lines) {
  vec_lines.push_back(str_header);
  std::vector<std::string> vec_fieldLines;
  DumpRecordFields(rec, vec_fieldLines);
  for (const std::string& str_line : vec_fieldLines)
    vec_lines.push_back(std::format("\t{}", str_line));
}

int RunDump(const std::string& str_mod, const std::string& str_upstreamRoot,
            const std::string& str_goldenFile, const bool b_checkMode) {
  gen::RegisterGeneratedAll();
  game::RegisterGameLoaders();

  game::InstalledMods mods_installed{str_upstreamRoot + "/mods"};
  const game::Manifest* manifest = mods_installed.Find(str_mod);
  if (manifest == nullptr) {
    std::println(stderr, "mod '{}' not found under {}/mods", str_mod, str_upstreamRoot);
    return 1;
  }

  game::ModData data_mod{*manifest, mods_installed, str_upstreamRoot};
  game::Ruleset& rules = data_mod.DefaultRules();

  std::vector<std::string> vec_lines;
  for (const auto& [str_name, rec_actor] : rules.Actors()) {
    vec_lines.push_back(std::format("== Actor {} ==", str_name));
    const auto& vec_traits = rec_actor->Traits();
    const auto& vec_instances = rec_actor->TraitInstanceNames();
    for (std::size_t int4_i{}; int4_i < vec_traits.size(); int4_i++) {
      const std::string str_header =
          vec_instances[int4_i].empty()
              ? std::format("Trait {}", vec_traits[int4_i]->record_desc().str_name)
              : std::format("Trait {}@{}",
                            vec_traits[int4_i]->record_desc().str_name,
                            vec_instances[int4_i]);
      DumpTraitInto(*vec_traits[int4_i], str_header, vec_lines);
    }
  }
  for (const auto& [str_name, rec_weapon] : rules.Weapons()) {
    vec_lines.push_back(std::format("== Weapon {} ==", str_name));
    std::vector<std::string> vec_fieldLines;
    DumpRecordFields(*rec_weapon, vec_fieldLines);
    for (const std::string& str_line : vec_fieldLines)
      vec_lines.push_back(std::format("\t{}", str_line));
  }
  for (const auto& [str_name, rec_voice] : rules.Voices()) {
    vec_lines.push_back(std::format("== VoiceSet {} ==", str_name));
    std::vector<std::string> vec_fieldLines;
    DumpRecordFields(*rec_voice, vec_fieldLines);
    for (const std::string& str_line : vec_fieldLines)
      vec_lines.push_back(std::format("\t{}", str_line));
  }
  for (const auto& [str_name, rec_note] : rules.Notifications()) {
    vec_lines.push_back(std::format("== Notification {} ==", str_name));
    std::vector<std::string> vec_fieldLines;
    DumpRecordFields(*rec_note, vec_fieldLines);
    for (const std::string& str_line : vec_fieldLines)
      vec_lines.push_back(std::format("\t{}", str_line));
  }
  for (const auto& [str_name, rec_music] : rules.Music()) {
    vec_lines.push_back(std::format("== Music {} ==", str_name));
    vec_lines.push_back(std::format("\tTitle: {}", rec_music->Title()));
    vec_lines.push_back(std::format("\tFilename: {}", rec_music->Filename()));
    vec_lines.push_back(std::format("\tHidden: {}", rec_music->Hidden() ? "True" : "False"));
    vec_lines.push_back(std::format("\tVolumeModifier: {}",
                                    meta::FormatFloatNet(rec_music->VolumeModifier())));
  }

  std::string str_dump;
  for (const std::string& str_line : vec_lines)
    str_dump += str_line + "\n";

  if (!b_checkMode) {
    std::print("{}", str_dump);
    return 0;
  }

  // 对拍:读黄金文件逐字节比 / compare: read the golden file, byte-diff.
  std::ifstream file_golden{str_goldenFile};
  if (!file_golden) {
    std::println(stderr, "golden file not readable: {}", str_goldenFile);
    return 1;
  }
  std::string str_golden{std::istreambuf_iterator<char>{file_golden},
                         std::istreambuf_iterator<char>{}};

  if (str_dump == str_golden) {
    std::println("golden_rules[{}]: {} lines match", str_mod, vec_lines.size());
    return 0;
  }

  // 首个差异定位 / locate the first difference.
  const std::vector<std::string> vec_goldenLines = [&] {
    std::vector<std::string> vec_ret;
    std::size_t int4_begin{};
    while (int4_begin <= str_golden.size()) {
      const std::size_t int4_nl = str_golden.find('\n', int4_begin);
      if (int4_nl == std::string::npos) {
        if (int4_begin < str_golden.size())
          vec_ret.emplace_back(str_golden.substr(int4_begin));
        break;
      }
      vec_ret.emplace_back(str_golden.substr(int4_begin, int4_nl - int4_begin));
      int4_begin = int4_nl + 1;
    }
    return vec_ret;
  }();
  std::size_t int4_first = 0;
  while (int4_first < vec_lines.size() && int4_first < vec_goldenLines.size() &&
         vec_lines[int4_first] == vec_goldenLines[int4_first])
    int4_first++;
  std::println(stderr, "golden_rules[{}]: MISMATCH at line {} (ours {} lines / golden {} lines)",
               str_mod, int4_first + 1, vec_lines.size(), vec_goldenLines.size());
  for (std::size_t int4_i = int4_first;
       int4_i < std::min<std::size_t>(vec_lines.size(), int4_first + 6); int4_i++)
    std::println(stderr, "  ours   | {}", vec_lines[int4_i]);
  for (std::size_t int4_i = int4_first;
       int4_i < std::min<std::size_t>(vec_goldenLines.size(), int4_first + 6); int4_i++)
    std::println(stderr, "  golden | {}", vec_goldenLines[int4_i]);
  return 1;
}

}  // namespace

int main(int argc, char** argv) {
  if (argc < 3) {
    std::println("usage: golden_rules <mod-id> <upstream-root> [golden-file]");
    std::println("       golden-file 提供时进入对拍模式,否则 dump 到 stdout");
    return 1;
  }
  const bool b_check = argc >= 4;
  try {
    return RunDump(argv[1], argv[2], argc >= 4 ? argv[3] : "", b_check);
  } catch (const std::exception& e_except) {
    std::println(stderr, "golden_rules: load failed: {}", e_except.what());
    return 1;
  }
}
